apiVersion: v1
kind: Service
metadata:
  name: worldbank-app-service
spec:
  selector:
    app: worldbank_app
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5001
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worldbank-app
spec:
  selector:
    matchLabels:
      app: worldbank-app
  replicas: 4
  template:
    metadata:
      labels:
        app: worldbank-app
    spec:
      containers:
      - name: worldbank-app
        image: worldbank_app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
